import React,{useMemo,useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import { App as CapacitorApp } from '@capacitor/app';
import {Menu,Home,Users,CalendarDays,Plus,UserCircle,Bell,Search,Upload,Edit3,Trash2,Save,ChevronRight,Building2,CheckCircle2,Image as ImageIcon,Download,Share2,BriefcaseBusiness,ShieldCheck,X} from 'lucide-react';
import './styles.css';

const SECTORS=['All','Healthcare','Automotive','Education','Construction','Hospitality','Food & Beverage','Retail & Trading','Technology','Finance & Consulting','Manufacturing','Media & Creative','Travel & Tourism','Real Estate','Professional Services'];
const CATEGORY_ICONS={
  'All':'🌐',
  'Healthcare':'🏥',
  'Automotive':'🚗',
  'Education':'🎓',
  'Construction':'🏗️',
  'Hospitality':'🏨',
  'Food & Beverage':'🍽️',
  'Retail & Trading':'🛍️',
  'Technology':'💻',
  'Finance & Consulting':'💼',
  'Manufacturing':'🏭',
  'Media & Creative':'🎬',
  'Travel & Tourism':'✈️',
  'Real Estate':'🏠',
  'Professional Services':'📋'
};

const seedMembers=[
  {
    "id": "m001",
    "name": "A. Hemanta Sharma",
    "position": "Dealer",
    "company": "NR Motors",
    "category": "Automotive",
    "email": "nrmotors_2017@yahoo.com",
    "phone": "9436893975",
    "address": "MG Avenue, Imphal - 795001, Manipur",
    "services": "Dealer - Mahindra Truck & Bus",
    "about": "NR Motors is listed as an approved AMBI/BEG member in the Automotive sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m002",
    "name": "Aadarsh Sharma",
    "position": "Managing Partner",
    "company": "Aadarsh Lab and Aadarsh Medicare Services",
    "category": "Healthcare",
    "email": "aadarshsharma1237@gmail.com",
    "phone": "7005242123",
    "address": "Imphal, Manipur",
    "services": "Diagnostic Centre / Aadarsh Medicare Services",
    "about": "Aadarsh Lab and Aadarsh Medicare Services is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m003",
    "name": "Abhishek Jain",
    "position": "Partner",
    "company": "Sangai Technologies",
    "category": "Technology",
    "email": "",
    "phone": "",
    "address": "Imphal, Manipur",
    "services": "Technology Services",
    "about": "Sangai Technologies is listed as an approved AMBI/BEG member in the Technology sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m004",
    "name": "Amardeep Singh Cheema",
    "position": "Director",
    "company": "MGT MOTORS PVT LTD",
    "category": "Automotive",
    "email": "asc@mgtmotors.com",
    "phone": "+919436025331",
    "address": "M G Avenue Imphal Manipur",
    "services": "Automobile Dealership",
    "about": "MGT MOTORS PVT LTD is listed as an approved AMBI/BEG member in the Automotive sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m005",
    "name": "Anand Sapam",
    "position": "Tax & Corporate Law Consultant",
    "company": "SA AND ASSOCIATES",
    "category": "Finance & Consulting",
    "email": "anand.sapam11@gmail.com",
    "phone": "9612904757",
    "address": "Keishamthong, Imphal West",
    "services": "Consultancy Services",
    "about": "SA AND ASSOCIATES is listed as an approved AMBI/BEG member in the Finance & Consulting sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m006",
    "name": "Angom Karna",
    "position": "Proprietor",
    "company": "Studio11 Salon and Spa, Fitness World, Ahong Achao Keithel",
    "category": "Retail & Trading",
    "email": "angomk.psd@gmail.com",
    "phone": "8731865955",
    "address": "Singjamei Mathak chongtham leikai, Kakching",
    "services": "Retail and service sector",
    "about": "Studio11 Salon and Spa, Fitness World, Ahong Achao Keithel is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m007",
    "name": "Anthony Naulak",
    "position": "Proprietor",
    "company": "Pollito's",
    "category": "Food & Beverage",
    "email": "",
    "phone": "",
    "address": "Singjamei Chingamathak",
    "services": "Food Service / Restaurant",
    "about": "Pollito's is listed as an approved AMBI/BEG member in the Food & Beverage sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m008",
    "name": "Arihant Patni",
    "position": "Partner",
    "company": "Sanmati Traders",
    "category": "Retail & Trading",
    "email": "",
    "phone": "",
    "address": "Imphal, Manipur",
    "services": "General Trading",
    "about": "Sanmati Traders is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m009",
    "name": "Ashangbam Vivekananda Singh",
    "position": "Proprietor",
    "company": "PADMA Medicare",
    "category": "Healthcare",
    "email": "padmamedicare2@gmail.com",
    "phone": "9446026455",
    "address": "RIMS Road, Near Nityanand Mandir",
    "services": "Medical / Healthcare",
    "about": "PADMA Medicare is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m010",
    "name": "Ashish Warepam",
    "position": "Proprietor",
    "company": "JCNT",
    "category": "Construction",
    "email": "ashish_w@outlook.com",
    "phone": "8415930129",
    "address": "Wangkhei Palace Compound, Imphal East-05, Manipur",
    "services": "Turnkey Solutions of Elevators, Fire Fighting & CCTV Surveillance",
    "about": "JCNT is listed as an approved AMBI/BEG member in the Construction sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m011",
    "name": "B. Surchandra Sharma",
    "position": "Secretary",
    "company": "The Fancier Educational Society, Thoubal",
    "category": "Education",
    "email": "fanciersur@gmail.com",
    "phone": "9862074363",
    "address": "Thoubal Wangmataba",
    "services": "Education",
    "about": "The Fancier Educational Society, Thoubal is listed as an approved AMBI/BEG member in the Education sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m012",
    "name": "Bachaspatimayum Indrashwor Sharma",
    "position": "Founder/Proprietor",
    "company": "Laisukol (school), Bachaspati drug agency (pharmacy)",
    "category": "Healthcare",
    "email": "indrashworsharma@gmail.com",
    "phone": "9612503024",
    "address": "Thoubal Bazar Makha, Thoubal Wangmataba",
    "services": "Human resources / sales",
    "about": "Laisukol (school), Bachaspati drug agency (pharmacy) is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m013",
    "name": "Bankim Nongthombam",
    "position": "Managing Director",
    "company": "Imphal Valley School; P.G Petroleum Agency; Sumati and Sons Group",
    "category": "Education",
    "email": "bankimnongthombam@gmail.com",
    "phone": "0385-2427613",
    "address": "Khabam, Chingmeirong, Moirangkhom Yaiskhul",
    "services": "Education; Retail",
    "about": "Imphal Valley School; P.G Petroleum Agency; Sumati and Sons Group is listed as an approved AMBI/BEG member in the Education sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m014",
    "name": "Benjamin Papao",
    "position": "Sound Wave",
    "company": "Benjamin Papao",
    "category": "Technology",
    "email": "",
    "phone": "",
    "address": "Churchandpur",
    "services": "Audio/Sound Services",
    "about": "Benjamin Papao is listed as an approved AMBI/BEG member in the Technology sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m015",
    "name": "Bigya Pheiroijam",
    "position": "Proprietor",
    "company": "Dotcom Computers",
    "category": "Technology",
    "email": "singhbigya31@gmail.com",
    "phone": "9862033771",
    "address": "Thangal Bazar, M.G. Avenue",
    "services": "Computer, Peripherals Sales & Service",
    "about": "Dotcom Computers is listed as an approved AMBI/BEG member in the Technology sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m016",
    "name": "Chingangbam Gulshan Singh",
    "position": "Proprietor",
    "company": "ALS IAS IMPHAL",
    "category": "Education",
    "email": "chingangbamg@gmail.com",
    "phone": "9856209399",
    "address": "Khurana Ahongei Leirak",
    "services": "Education",
    "about": "ALS IAS IMPHAL is listed as an approved AMBI/BEG member in the Education sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m017",
    "name": "Chingshubam Ashok Meetei",
    "position": "Managing Director",
    "company": "Meetei Construction Pvt Ltd",
    "category": "Education",
    "email": "ashok@meeteicpl.com",
    "phone": "9862223333",
    "address": "Porompat and Ayangpalli Road",
    "services": "Construction & School",
    "about": "Meetei Construction Pvt Ltd is listed as an approved AMBI/BEG member in the Education sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m018",
    "name": "Chongtham Punshiba Singh",
    "position": "Owner",
    "company": "Bath Gallery",
    "category": "Retail & Trading",
    "email": "punshi11@rediffmail.com",
    "phone": "9862033724",
    "address": "Khabam lamkhai",
    "services": "Tiles and sanitary",
    "about": "Bath Gallery is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m019",
    "name": "Dayanand Thounaojam",
    "position": "Proprietor",
    "company": "Tilakraj Enterprises",
    "category": "Manufacturing",
    "email": "daya7us@gmail.com",
    "phone": "700585361",
    "address": "Thangal Bazar, opp. Kasturi Building, Imphal",
    "services": "Manufacturing & sales of Souvenirs, Trophy, Memento, Rubber stamp, Medals and Brass handicrafts",
    "about": "Tilakraj Enterprises is listed as an approved AMBI/BEG member in the Manufacturing sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m020",
    "name": "Donny Sharma",
    "position": "Distributor",
    "company": "Radha Enterprises (Fleet Guard filter pvt ltd and Mico)",
    "category": "Retail & Trading",
    "email": "risonsmotors14@gmail.com",
    "phone": "8787574740",
    "address": "Khoyathong Bazar",
    "services": "Distribution",
    "about": "Radha Enterprises (Fleet Guard filter pvt ltd and Mico) is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m021",
    "name": "Dr M. Dayananda (Pibarel)",
    "position": "Managing Director",
    "company": "Medilane Healthtech And Consultancy Services Private Limited",
    "category": "Healthcare",
    "email": "medilane.in@gmail.com",
    "phone": "9366538001",
    "address": "Porompat Near JNIMS Hospital, Imphal East, Manipur",
    "services": "Healthcare",
    "about": "Medilane Healthtech And Consultancy Services Private Limited is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m022",
    "name": "Dr Ibomcha Thokchom",
    "position": "Founder & Managing Director",
    "company": "Advanced Hospital",
    "category": "Healthcare",
    "email": "ithokcho@yahoo.co.in",
    "phone": "+919436026045",
    "address": "Palace Compound, Imphal East",
    "services": "Healthcare",
    "about": "Advanced Hospital is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m023",
    "name": "Dr James Elangbam",
    "position": "Managing Director",
    "company": "Acme Fertility & HealthCare Centre",
    "category": "Healthcare",
    "email": "acmefertility@gmail.com",
    "phone": "6909158069",
    "address": "Hiyang Hiren Leirak, Palace Compound, Imphal East",
    "services": "IVF Centre and Gynecological Centre",
    "about": "Acme Fertility & HealthCare Centre is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m024",
    "name": "Elizabeth Yambem",
    "position": "Member",
    "company": "Dweller Tea",
    "category": "Food & Beverage",
    "email": "",
    "phone": "",
    "address": "Lamphel",
    "services": "Beverage/Tea Retail",
    "about": "Dweller Tea is listed as an approved AMBI/BEG member in the Food & Beverage sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m025",
    "name": "Gautam Sharma Shamurailatpam",
    "position": "Executive Editor",
    "company": "The People's Chronicle / Poknapham",
    "category": "Media & Creative",
    "email": "shgautam79@gmail.com",
    "phone": "9436021276",
    "address": "Imphal, Manipur",
    "services": "Media n printing press / Padma printers",
    "about": "The People's Chronicle / Poknapham is listed as an approved AMBI/BEG member in the Media & Creative sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m026",
    "name": "Gitkumar Nepram",
    "position": "Member",
    "company": "Habitat World (Habitat Design Studio)",
    "category": "Professional Services",
    "email": "",
    "phone": "",
    "address": "Sagolband",
    "services": "Architecture/Design",
    "about": "Habitat World (Habitat Design Studio) is listed as an approved AMBI/BEG member in the Professional Services sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m027",
    "name": "Hero Thokchom",
    "position": "Managing Director",
    "company": "Iboyaima Hospital & Research centre / Golden Transpower / Iboyaima & Sons",
    "category": "Healthcare",
    "email": "hthokchom@yahoo.co.in",
    "phone": "7005123802",
    "address": "Singjamei Mathak Chongtham Leikai",
    "services": "Healthcare Products",
    "about": "Iboyaima Hospital & Research centre / Golden Transpower / Iboyaima & Sons is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m028",
    "name": "Hodam Priyokumar",
    "position": "President",
    "company": "Fancier Educational Society",
    "category": "Education",
    "email": "fancierpriyo@gmail.com",
    "phone": "9612501599",
    "address": "Thoubal Okram Wangmataba, Thoubal",
    "services": "Education",
    "about": "Fancier Educational Society is listed as an approved AMBI/BEG member in the Education sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m029",
    "name": "Huidrom Bigyanjit Singh",
    "position": "Director",
    "company": "HVS Construction Materials Pvt Ltd",
    "category": "Construction",
    "email": "bigyanjit_huidrom@yahoo.com",
    "phone": "8415902857",
    "address": "Patsoi part 1, New Cacchhar road",
    "services": "Construction",
    "about": "HVS Construction Materials Pvt Ltd is listed as an approved AMBI/BEG member in the Construction sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m030",
    "name": "Irom Umakanta Singh",
    "position": "Managing Director",
    "company": "COMET School And Coaching institute",
    "category": "Education",
    "email": "usingirom@gmail.com",
    "phone": "9612637445",
    "address": "Changangei Uchekon n Keishampat",
    "services": "Education",
    "about": "COMET School And Coaching institute is listed as an approved AMBI/BEG member in the Education sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m031",
    "name": "Jacky Sharma Shamurailatpam",
    "position": "Member",
    "company": "Adarsh Lab (Aadarsh Medicare Services)",
    "category": "Healthcare",
    "email": "",
    "phone": "",
    "address": "Porompat",
    "services": "Healthcare Services",
    "about": "Adarsh Lab (Aadarsh Medicare Services) is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m032",
    "name": "James Kangabam",
    "position": "Proprietor",
    "company": "Shree Manikumar Jewellery",
    "category": "Retail & Trading",
    "email": "jameskangabam123@gmail.com",
    "phone": "7005130776",
    "address": "Sagolband kangabam Leikai",
    "services": "Retail",
    "about": "Shree Manikumar Jewellery is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m033",
    "name": "Javed Siddique",
    "position": "Proprietor",
    "company": "JS PLY",
    "category": "Manufacturing",
    "email": "jst237@gmail.com",
    "phone": "",
    "address": "Thangal bazar / Mantripukhri",
    "services": "Plywood, Laminates, MDF, etc.",
    "about": "JS PLY is listed as an approved AMBI/BEG member in the Manufacturing sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m034",
    "name": "Jayananda",
    "position": "Member",
    "company": "Jayananda United Enterprises",
    "category": "Retail & Trading",
    "email": "",
    "phone": "",
    "address": "Imphal, Manipur",
    "services": "Trade/Enterprise",
    "about": "Jayananda United Enterprises is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m035",
    "name": "Jiten Sharma Aribam",
    "position": "Proprietor",
    "company": "Sharma Associates",
    "category": "Travel & Tourism",
    "email": "jiten_sharmaa@yahoo.co.in",
    "phone": "09862241741",
    "address": "Thoubal Bazar",
    "services": "Travel/tourism and Garment's",
    "about": "Sharma Associates is listed as an approved AMBI/BEG member in the Travel & Tourism sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m036",
    "name": "Kangjam Dinesh",
    "position": "Member",
    "company": "OPPO",
    "category": "Technology",
    "email": "",
    "phone": "",
    "address": "Nongmeibung",
    "services": "Telecommunications/Retail",
    "about": "OPPO is listed as an approved AMBI/BEG member in the Technology sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m037",
    "name": "KB Pangambam",
    "position": "Proprietor",
    "company": "KB Enterprises",
    "category": "Travel & Tourism",
    "email": "kbento@gmail.com",
    "phone": "9862028656",
    "address": "MG Avenue, Imphal",
    "services": "Tour Operator (Forex, Visa, Passports, Ticketing, Inbound & Outbound)",
    "about": "KB Enterprises is listed as an approved AMBI/BEG member in the Travel & Tourism sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m038",
    "name": "Khaba Sanabam",
    "position": "Proprietor",
    "company": "Reliable Sales",
    "category": "Automotive",
    "email": "khabasanabam@gmail.com",
    "phone": "09862576922",
    "address": "Thangal Bazar, Khoyathong Road",
    "services": "Motor Parts",
    "about": "Reliable Sales is listed as an approved AMBI/BEG member in the Automotive sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m039",
    "name": "Khagemba Sanabam",
    "position": "Managing Director",
    "company": "Manipur Oxygen Plant Pvt. Ltd.",
    "category": "Healthcare",
    "email": "ksanabam@gmail.com",
    "phone": "09862569861",
    "address": "Ward no.10, Bishnupur District",
    "services": "Medical and industrial oxygen",
    "about": "Manipur Oxygen Plant Pvt. Ltd. is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m040",
    "name": "Kiltan Maibam",
    "position": "Businessman",
    "company": "Airport Shopping Mall",
    "category": "Automotive",
    "email": "kiltan_maibam24@yahoo.com",
    "phone": "7085557176",
    "address": "Changangei airport road, Opp. Imphal Airport",
    "services": "Furnitures & Furnishing",
    "about": "Airport Shopping Mall is listed as an approved AMBI/BEG member in the Automotive sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m041",
    "name": "Kshetrimayum Rustamkumar Singh",
    "position": "Proprietor",
    "company": "M/s Wangbrel decor",
    "category": "Retail & Trading",
    "email": "kshrustamkumar@gmail.com",
    "phone": "8413877340",
    "address": "Singjamei chinga mathak opposite UCO Bank",
    "services": "Home and office Furniture showroom",
    "about": "M/s Wangbrel decor is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m042",
    "name": "L Sanatombi Devi",
    "position": "Chairman",
    "company": "Iboyaima Group",
    "category": "Healthcare",
    "email": "thokongbisana@gmail.com",
    "phone": "9436890363",
    "address": "Singjamei Mathak Chongtham leikai",
    "services": "Health care, Finance, Power, Construction",
    "about": "Iboyaima Group is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m043",
    "name": "Laishram Brijkeshowr Singh",
    "position": "Proprietor",
    "company": "Phou-Oi-Bee hotel",
    "category": "Hospitality",
    "email": "brijkishowr86@gmail.com",
    "phone": "8731921044",
    "address": "North AOC Imphal",
    "services": "Hotel",
    "about": "Phou-Oi-Bee hotel is listed as an approved AMBI/BEG member in the Hospitality sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m044",
    "name": "Laishram Kishan Singh",
    "position": "Proprietor",
    "company": "Kishan Eco Plastic Industry",
    "category": "Manufacturing",
    "email": "kepimd26@gmail.com",
    "phone": "7005402125",
    "address": "Tera Urak Industrial Estate, Bishnupur",
    "services": "Manufacturing PVC pipes",
    "about": "Kishan Eco Plastic Industry is listed as an approved AMBI/BEG member in the Manufacturing sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m045",
    "name": "Leishangtham Ronel Singh",
    "position": "Member",
    "company": "RSRS",
    "category": "Professional Services",
    "email": "",
    "phone": "",
    "address": "Patsoi",
    "services": "Transport/Services",
    "about": "RSRS is listed as an approved AMBI/BEG member in the Professional Services sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m046",
    "name": "M Geetaranjan Sharma",
    "position": "Member",
    "company": "LISMART INDUSTRIES",
    "category": "Manufacturing",
    "email": "lismart_sangai@yahoo.in",
    "phone": "0385-2412377 / 986209740",
    "address": "84/Shop-cum Res. Complex (Super Market) Lamphel",
    "services": "Sangai Plastic water storage tank & Sangai UPVC pipes, sewage pipes",
    "about": "LISMART INDUSTRIES is listed as an approved AMBI/BEG member in the Manufacturing sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m047",
    "name": "N. Dhinel Singh",
    "position": "Proprietor",
    "company": "ND INDUSTRIES",
    "category": "Manufacturing",
    "email": "ndhinelsingh@gmail.com",
    "phone": "8974036490",
    "address": "Mantripukhri, Imphal",
    "services": "Package Drinking Water - Bisleri Brand",
    "about": "ND INDUSTRIES is listed as an approved AMBI/BEG member in the Manufacturing sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m048",
    "name": "Nishant Patni",
    "position": "Member",
    "company": "PCTC",
    "category": "Professional Services",
    "email": "",
    "phone": "",
    "address": "Imphal, Manipur",
    "services": "Transport/Logistics",
    "about": "PCTC is listed as an approved AMBI/BEG member in the Professional Services sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m049",
    "name": "P Kebi Singh",
    "position": "Partner",
    "company": "Geo-Environmental & Technical Services",
    "category": "Professional Services",
    "email": "kebimphal@gmail.com",
    "phone": "09774196652",
    "address": "Opposite Manipur University",
    "services": "Geophysical Services, etc.",
    "about": "Geo-Environmental & Technical Services is listed as an approved AMBI/BEG member in the Professional Services sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m050",
    "name": "Pheiroijam Romikanta Singh",
    "position": "Member",
    "company": "Iland Nissan",
    "category": "Automotive",
    "email": "",
    "phone": "",
    "address": "Canchipur",
    "services": "Automobile Dealership",
    "about": "Iland Nissan is listed as an approved AMBI/BEG member in the Automotive sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m051",
    "name": "Potsangbam Tomba",
    "position": "Member",
    "company": "Tomba Enterprises",
    "category": "Construction",
    "email": "",
    "phone": "",
    "address": "Singjamei Chingamakha",
    "services": "Construction",
    "about": "Tomba Enterprises is listed as an approved AMBI/BEG member in the Construction sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m052",
    "name": "Pradeep Singh Meitram",
    "position": "Chief Executive Officer",
    "company": "Elle's Group",
    "category": "Food & Beverage",
    "email": "psmeitram@gmail.com",
    "phone": "7005203128",
    "address": "#22, PDA Complex, Lamphelpat, Imphal, Manipur",
    "services": "Bakery, interior solutions, IT & communications, skill development",
    "about": "Elle's Group is listed as an approved AMBI/BEG member in the Food & Beverage sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m053",
    "name": "Puyam Surchand Singh",
    "position": "Managing Director",
    "company": "Siroi financial consultancy Pvt Ltd",
    "category": "Finance & Consulting",
    "email": "surchandp@gmail.com",
    "phone": "8118925964",
    "address": "MG Avenue",
    "services": "Financial Services",
    "about": "Siroi financial consultancy Pvt Ltd is listed as an approved AMBI/BEG member in the Finance & Consulting sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m054",
    "name": "Radhesyam Oinam",
    "position": "Chief Coordinator",
    "company": "Network Services",
    "category": "Retail & Trading",
    "email": "radhesyamoinam@yahoo.com",
    "phone": "9436026403",
    "address": "Changangei Uchekon, Imphal West",
    "services": "Retail Servicing",
    "about": "Network Services is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m055",
    "name": "Rakesh Konjengbam",
    "position": "Founder",
    "company": "Ingenix Educare",
    "category": "Education",
    "email": "rakesh.konjengbam@gmail.com",
    "phone": "8730935858",
    "address": "Konung Mamang New Checkon Road",
    "services": "Career Guidance and Counseling",
    "about": "Ingenix Educare is listed as an approved AMBI/BEG member in the Education sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m056",
    "name": "Rakesh Takhellambam",
    "position": "Member",
    "company": "Indra Eye Care",
    "category": "Healthcare",
    "email": "",
    "phone": "",
    "address": "RIMS Road",
    "services": "Eye care products",
    "about": "Indra Eye Care is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m057",
    "name": "Ramesh Urikhaibam",
    "position": "Member",
    "company": "Pranab Motors",
    "category": "Automotive",
    "email": "",
    "phone": "",
    "address": "Mayang Imphal",
    "services": "Automotive Retail",
    "about": "Pranab Motors is listed as an approved AMBI/BEG member in the Automotive sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m058",
    "name": "Ripujeet Nongthombam",
    "position": "Managing Director",
    "company": "Lee Waa Group",
    "category": "Construction",
    "email": "carter.nongthombam@gmail.com",
    "phone": "+916009874675",
    "address": "Ghari Awang Leikai",
    "services": "Construction, Design & Supply",
    "about": "Lee Waa Group is listed as an approved AMBI/BEG member in the Construction sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m059",
    "name": "Rishikesh Khundongbam",
    "position": "Managing Director",
    "company": "Mipax Real Estate Consultant Pvt. Ltd.",
    "category": "Finance & Consulting",
    "email": "rishikesh.kh36@gmail.com",
    "phone": "7005230583",
    "address": "Sangaiprou (Opposite FCS Godown), Imphal West",
    "services": "Real Estate Syndication, Development Consultant & PMC",
    "about": "Mipax Real Estate Consultant Pvt. Ltd. is listed as an approved AMBI/BEG member in the Finance & Consulting sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m060",
    "name": "RK Budhisaran",
    "position": "Member",
    "company": "Pioneer Trading",
    "category": "Retail & Trading",
    "email": "",
    "phone": "",
    "address": "Keisamthong",
    "services": "General Trading",
    "about": "Pioneer Trading is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m061",
    "name": "Vinykesh Patni",
    "position": "Director",
    "company": "Dhana Lakshmi Pvt Ltd",
    "category": "Hospitality",
    "email": "vinykesh.patni@vpgroup.co.in",
    "phone": "9862558958",
    "address": "Padma Bhawan, Dharamsala Road",
    "services": "Pharmaceuticals, FMCG, Hotel",
    "about": "Dhana Lakshmi Pvt Ltd is listed as an approved AMBI/BEG member in the Hospitality sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m062",
    "name": "Vitoo Oinam",
    "position": "Co-founder and Managing Director",
    "company": "SF Delivery (Soultifaction Online Services LLP)",
    "category": "Food & Beverage",
    "email": "info@soultifaction.com",
    "phone": "9077808818",
    "address": "New Checkon Road, Imphal - 795005",
    "services": "Online Food Delivery",
    "about": "SF Delivery (Soultifaction Online Services LLP) is listed as an approved AMBI/BEG member in the Food & Beverage sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m063",
    "name": "Wangkheimayum Khoma",
    "position": "Member",
    "company": "Sanamahi Motors",
    "category": "Automotive",
    "email": "",
    "phone": "",
    "address": "Singjamei Chingamathak",
    "services": "Automotive Support",
    "about": "Sanamahi Motors is listed as an approved AMBI/BEG member in the Automotive sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m064",
    "name": "Wangkheimayum Vikram",
    "position": "Managing Director",
    "company": "The Sangai Hotel",
    "category": "Hospitality",
    "email": "vikram_sana@yahoo.com",
    "phone": "9612164935",
    "address": "Nagamapal, Lamabam Leikai, Imphal, Manipur",
    "services": "Hotel",
    "about": "The Sangai Hotel is listed as an approved AMBI/BEG member in the Hospitality sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m065",
    "name": "Wangkhem Lenin",
    "position": "Member",
    "company": "W. Ibohal Singh & Sons",
    "category": "Retail & Trading",
    "email": "",
    "phone": "",
    "address": "W. Ibohal Singh & Sons",
    "services": "Trading/Retail",
    "about": "W. Ibohal Singh & Sons is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m066",
    "name": "Y Ashok Kumar",
    "position": "Member",
    "company": "Leibaklei Hotel",
    "category": "Healthcare",
    "email": "",
    "phone": "",
    "address": "Jiri",
    "services": "Hospitality",
    "about": "Leibaklei Hotel is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m067",
    "name": "Yanglem Surjeet",
    "position": "Proprietor",
    "company": "Fastrack Signage",
    "category": "Media & Creative",
    "email": "yangsurjeet@gmail.com",
    "phone": "9856080024",
    "address": "Thangmeiband Watham Leirai",
    "services": "Sign and banner service",
    "about": "Fastrack Signage is listed as an approved AMBI/BEG member in the Media & Creative sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m068",
    "name": "Yumnam Rupachandra Singh",
    "position": "Editor in Chief",
    "company": "Impact TV News",
    "category": "Media & Creative",
    "email": "yumnamrupa@gmail.com",
    "phone": "9612158469",
    "address": "Paona Bazar, Imphal West, Manipur",
    "services": "Electronic Media (News)",
    "about": "Impact TV News is listed as an approved AMBI/BEG member in the Media & Creative sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m069",
    "name": "RK Nisha",
    "position": "Member",
    "company": "Bubble Beats",
    "category": "Professional Services",
    "email": "",
    "phone": "",
    "address": "Keisampat",
    "services": "Childhood/Play Programs",
    "about": "Bubble Beats is listed as an approved AMBI/BEG member in the Professional Services sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m070",
    "name": "RK Rameshwar",
    "position": "Member",
    "company": "RK Fortune",
    "category": "Construction",
    "email": "",
    "phone": "",
    "address": "Changangei",
    "services": "Construction",
    "about": "RK Fortune is listed as an approved AMBI/BEG member in the Construction sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m071",
    "name": "Robin Seram",
    "position": "Managing Director",
    "company": "Epic Films Imphal",
    "category": "Media & Creative",
    "email": "robinseram@gmail.com",
    "phone": "08974615771",
    "address": "Nongmeibung Seram Leirak, Imphal East",
    "services": "Advertising Agency & Photo-Video Production House",
    "about": "Epic Films Imphal is listed as an approved AMBI/BEG member in the Media & Creative sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m072",
    "name": "Sadokpam Itombi Singh",
    "position": "Proprietor",
    "company": "S J Plastic Agency",
    "category": "Manufacturing",
    "email": "sjplasticagency@gmail.com",
    "phone": "9612410442",
    "address": "Sagolband Sadokpam Leikai",
    "services": "Manufacturing plastic households items",
    "about": "S J Plastic Agency is listed as an approved AMBI/BEG member in the Manufacturing sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m073",
    "name": "Santosh Saikhom",
    "position": "Member",
    "company": "Santosh Electronics",
    "category": "Technology",
    "email": "",
    "phone": "",
    "address": "Moreh",
    "services": "Electronics Retail",
    "about": "Santosh Electronics is listed as an approved AMBI/BEG member in the Technology sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m074",
    "name": "Sinam Haridas Singh",
    "position": "Member",
    "company": "Eastern Motors",
    "category": "Automotive",
    "email": "",
    "phone": "",
    "address": "Mantripukhri",
    "services": "Automotive Supply",
    "about": "Eastern Motors is listed as an approved AMBI/BEG member in the Automotive sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m075",
    "name": "Sougaijam Brainy",
    "position": "Member",
    "company": "SB & Sons",
    "category": "Retail & Trading",
    "email": "",
    "phone": "",
    "address": "Moirangkhom",
    "services": "Retail/Trade",
    "about": "SB & Sons is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m076",
    "name": "Thangjam Arunkumar",
    "position": "Member",
    "company": "Arun Enterprises",
    "category": "Retail & Trading",
    "email": "",
    "phone": "",
    "address": "Chingmeirong",
    "services": "Commercial Enterprises",
    "about": "Arun Enterprises is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m077",
    "name": "Thangjam Roshan Singh",
    "position": "Director",
    "company": "AMP E SERVICES PVT LTD",
    "category": "Technology",
    "email": "roshanamp@gmail.com",
    "phone": "8132953246",
    "address": "Paona Bazar, Imphal, Manipur",
    "services": "Electronics and Mobile",
    "about": "AMP E SERVICES PVT LTD is listed as an approved AMBI/BEG member in the Technology sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m078",
    "name": "Thoudam Shanjubala Devi",
    "position": "Proprietor",
    "company": "SAS Enterprises",
    "category": "Retail & Trading",
    "email": "sharjubala@gmail.com",
    "phone": "8974053214",
    "address": "Thoubal Awang Leikai, Thoubal 795138",
    "services": "FMCG",
    "about": "SAS Enterprises is listed as an approved AMBI/BEG member in the Retail & Trading sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m079",
    "name": "Tongbram Tarunkumar",
    "position": "Proprietor",
    "company": "Kohort Design & Build",
    "category": "Construction",
    "email": "kohort.design@gmail.com",
    "phone": "8257811079",
    "address": "Singjamei Mathak Chongtham Leikai",
    "services": "Building Planning and Construction",
    "about": "Kohort Design & Build is listed as an approved AMBI/BEG member in the Construction sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  },
  {
    "id": "m080",
    "name": "Vincent Koijam",
    "position": "Director",
    "company": "Daani Hotels and Resorts Pvt Ltd",
    "category": "Healthcare",
    "email": "vincentkoijam@gmail.com",
    "phone": "8730922881",
    "address": "Thangmeiband",
    "services": "Hospitality",
    "about": "Daani Hotels and Resorts Pvt Ltd is listed as an approved AMBI/BEG member in the Healthcare sector.",
    "display": "initials",
    "photo": "",
    "logo": "",
    "verified": true,
    "approvedBy": "AMBI Directory Import"
  }
];
const blank={name:'',position:'',company:'',category:'Healthcare',email:'',phone:'',address:'',services:'',about:'',display:'initials',photo:'',logo:'',verified:true,approvedBy:'Admin'};
function initials(name,company){const source=(company||name||'AMBI').trim().split(/\s+/);return source.slice(0,2).map(s=>s[0]).join('').toUpperCase();}
function Avatar({m,big=false}){let src=m.display==='photo'?m.photo:m.display==='logo'?m.logo:'';return src?<img className={big?'avatarImg big':'avatarImg'} src={src}/>:<div className={big?'avatarMono big':'avatarMono'}>{initials(m.name,m.company)}</div>}
function readFile(file,cb){if(!file)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}

const profileActivity=[
 {id:'a1',type:'Advertisement',title:'Submitted business promotion banner',status:'Approved',date:'This month',approvedBy:'Committee Admin'},
 {id:'a2',type:'Event',title:'RSVP confirmed for Business Networking Evening',status:'Completed',date:'Last week',approvedBy:'AMBI'},
 {id:'a3',type:'Profile',title:'Updated digital visiting card details',status:'Completed',date:'Today',approvedBy:'Member'}
];


const seedCalendarEvents=[
 {id:'hol-jan26',title:'Republic Day',date:'2026-01-26',time:'All day',location:'India',createdBy:'Indian National Calendar',type:'National Holiday',source:'Official national holiday',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-mar03',title:'Yaoshang begins',date:'2026-03-03',time:'All day',location:'Manipur',createdBy:'Manipuri Cultural Calendar',type:'Manipuri Festival',source:'Yaoshang/Holi season',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-mar04',title:'Holi',date:'2026-03-04',time:'All day',location:'India',createdBy:'Indian Holiday Calendar',type:'Festival',source:'Indian festival calendar',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-mar26',title:'Ram Navami',date:'2026-03-26',time:'All day',location:'India',createdBy:'Indian Holiday Calendar',type:'Festival',source:'Indian festival calendar',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-apr03',title:'Good Friday',date:'2026-04-03',time:'All day',location:'India',createdBy:'Indian Holiday Calendar',type:'National/Religious Holiday',source:'Indian holiday calendar',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-apr14',title:'Cheiraoba / Sajibu Nongma Panba',date:'2026-04-14',time:'All day',location:'Manipur',createdBy:'Manipuri Cultural Calendar',type:'Manipuri Festival',source:'Meitei New Year, date may follow local lunar notification',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-may01',title:'Buddha Purnima',date:'2026-05-01',time:'All day',location:'India',createdBy:'Indian Holiday Calendar',type:'Festival',source:'Indian festival calendar',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-aug15',title:'Independence Day',date:'2026-08-15',time:'All day',location:'India',createdBy:'Indian National Calendar',type:'National Holiday',source:'Official national holiday',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-oct02',title:'Gandhi Jayanti',date:'2026-10-02',time:'All day',location:'India',createdBy:'Indian National Calendar',type:'National Holiday',source:'Official national holiday',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-oct20',title:'Dussehra / Vijayadashami',date:'2026-10-20',time:'All day',location:'India',createdBy:'Indian Holiday Calendar',type:'Festival',source:'Indian festival calendar',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-nov08',title:'Diwali / Deepavali',date:'2026-11-08',time:'All day',location:'India',createdBy:'Indian Holiday Calendar',type:'Festival',source:'Indian festival calendar',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-nov10',title:'Ningol Chakouba',date:'2026-11-10',time:'All day',location:'Manipur',createdBy:'Manipuri Cultural Calendar',type:'Manipuri Festival',source:'Meitei lunar festival, verify with local 2026 notification',attending:[],maybe:[],not:[],blocked:false},
 {id:'hol-dec25',title:'Christmas Day',date:'2026-12-25',time:'All day',location:'India',createdBy:'Indian Holiday Calendar',type:'National/Religious Holiday',source:'Indian holiday calendar',attending:[],maybe:[],not:[],blocked:false},
 {id:'beg-jun24',title:'BEG Business Networking Evening',date:'2026-06-24',time:'4:00 PM',location:'BEG Office',createdBy:'AMBI Members',type:'Member Event',source:'AMBI event',attending:['Aadarsh Sharma','Anand Sapam'],maybe:['Robin Seram'],not:[],blocked:false},
 {id:'beg-jun28',title:'Member Directory Review Meet',date:'2026-06-28',time:'11:00 AM',location:'Imphal',createdBy:'AMBI Members',type:'Member Event',source:'AMBI event',attending:['A. Hemanta Sharma'],maybe:[],not:[],blocked:false}
];

const notificationSeed=[
 {t:'Calendar is open for members',d:'Approved members can now create calendar items directly. Admins can remove inappropriate events.'},
 {t:'2026 holiday calendar installed',d:'Indian national holidays and key Manipuri cultural observances are listed in Calendar.'},
 {t:'Directory loaded',d:'All 80 approved AMBI/BEG members are available in the directory.'}
];
function dateParts(iso){const [y,m,d]=String(iso).split('-').map(Number);return {year:y,month:m-1,day:d}}
function monthName(i){return ['January','February','March','April','May','June','July','August','September','October','November','December'][i]}
function eventKeyDate(ev){return ev.date || `2026-06-${String(ev.day||1).padStart(2,'0')}`}

function App(){const [page,setPageRaw]=useState('home');const [drawer,setDrawer]=useState(false);const [members,setMembers]=useState(()=>{try{return JSON.parse(localStorage.getItem('ambiMembersRealV2'))||seedMembers}catch{return seedMembers}});const [query,setQuery]=useState('');const [cat,setCat]=useState('All');const [selected,setSelected]=useState(seedMembers[0]);const [form,setForm]=useState(blank);const [editing,setEditing]=useState(null);const [toast,setToast]=useState('');const [loggedIn,setLoggedIn]=useState(()=>localStorage.getItem('ambiLoggedIn')!=='false');const [contacts,setContacts]=useState(()=>{try{return JSON.parse(localStorage.getItem('ambiContactsV18'))||[]}catch{return []}});const [calendarEvents,setCalendarEvents]=useState(()=>{try{const saved=JSON.parse(localStorage.getItem('ambiCalendarEventsV19'));return Array.isArray(saved)&&saved.length?saved:seedCalendarEvents}catch{return seedCalendarEvents}});const pageRef=useRef(page);const lastBackRef=useRef(0);const historyReadyRef=useRef(false);const setPage=(next)=>{setPageRaw(prev=>{const target=typeof next==='function'?next(prev):next;if(target&&target!==prev){pageRef.current=target;if(historyReadyRef.current&&typeof window!=='undefined'){window.history.pushState({ambiPage:target},'',`${window.location.pathname}${window.location.search}#${target}`)}}return target||prev})};useEffect(()=>{pageRef.current=page},[page]);useEffect(()=>{if(typeof window==='undefined')return;if(!window.history.state?.ambiPage){window.history.replaceState({ambiPage:'home'},'',`${window.location.pathname}${window.location.search}#home`)}historyReadyRef.current=true;const onPop=()=>{const target=window.history.state?.ambiPage||'home';pageRef.current=target;setPageRaw(target)};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);useEffect(()=>{let handle;CapacitorApp.addListener('backButton',()=>{const current=pageRef.current;if(current&&current!=='home'){setPage('home');return}const now=Date.now();if(now-lastBackRef.current<2000){CapacitorApp.exitApp();return}lastBackRef.current=now;setToast('Press back again to exit')}).then(h=>{handle=h}).catch(()=>{});return()=>{if(handle&&handle.remove)handle.remove()}},[]);useEffect(()=>localStorage.setItem('ambiMembersRealV2',JSON.stringify(members)),[members]);useEffect(()=>localStorage.setItem('ambiLoggedIn',loggedIn?'true':'false'),[loggedIn]);useEffect(()=>localStorage.setItem('ambiContactsV18',JSON.stringify(contacts)),[contacts]);useEffect(()=>localStorage.setItem('ambiCalendarEventsV19',JSON.stringify(calendarEvents)),[calendarEvents]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(t)}},[toast]);const filtered=useMemo(()=>members.filter(m=>(cat==='All'||m.category===cat)&&(`${m.name} ${m.company} ${m.category} ${m.services}`.toLowerCase().includes(query.toLowerCase()))),[members,cat,query]);const sectors=SECTORS.map(s=>({name:s,count:s==='All'?members.length:members.filter(m=>m.category===s).length}));function saveMember(){if(!form.name||!form.company){setToast('Name and company are required');return} if(editing){setMembers(ms=>ms.map(m=>m.id===editing?{...form,id:editing}:m));setToast('Member profile updated')}else{setMembers(ms=>[{...form,id:'m'+Date.now()},...ms]);setToast('New member saved to directory')}setForm(blank);setEditing(null);setPage('directory')}function edit(m){setForm(m);setEditing(m.id);setPage('management')}function del(id){setMembers(ms=>ms.filter(m=>m.id!==id));setToast('Member deleted from local directory')}function openProfile(m){if(selected?.id&&m.id!==selected.id){setContacts(cs=>cs.some(c=>c.id===m.id)?cs:[{id:m.id,name:m.name,company:m.company,date:new Date().toLocaleDateString()},...cs].slice(0,8));}setSelected(m);setPage('profile')}function logout(){setLoggedIn(false);setToast('Logged out successfully');setPage('profile')}function login(){setLoggedIn(true);setToast('Logged in');setPage('profile')}return <div className="app"><header className="topbar"><button className="iconBtn" onClick={()=>setDrawer(true)}><Menu/></button><button className="brand brandButton" onClick={()=>setPage('home')} aria-label="Go to Home"><img src="/ambi-logo.png"/><div><strong>AMBI</strong><small>Business Excellence Group</small></div></button><nav><button className={page==='home'?'active':''} onClick={()=>setPage('home')}>Home</button><button className={page==='about'?'active':''} onClick={()=>setPage('about')}>About</button><button className={page==='directory'?'active':''} onClick={()=>setPage('directory')}>Directory</button><button className={(page==='calendar'||page==='reminder')?'active':''} onClick={()=>setPage('calendar')}>Calendar</button></nav><button className="notif" onClick={()=>setPage('notifications')}><Bell/><span>3</span></button></header>{drawer&&<div className="overlay" onClick={()=>setDrawer(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><img src="/ambi-logo.png"/><div><b>AMBI</b><small>Members App</small></div><button onClick={()=>setDrawer(false)}><X/></button></div>{['home','about','directory','calendar','submit','notifications','management'].map(p=><button key={p} className={(page===p||(p==='calendar'&&page==='reminder'))?'active':''} onClick={()=>{setPage(p);setDrawer(false)}}>{p==='calendar'?'Calendar':p[0].toUpperCase()+p.slice(1)}</button>)}</aside></div>}<main>{page==='home'&&<HomePage members={members} calendarEvents={calendarEvents} setPage={setPage} openProfile={openProfile}/>} {page==='directory'&&<Directory members={filtered} sectors={sectors} cat={cat} setCat={setCat} query={query} setQuery={setQuery} openProfile={openProfile}/>} {page==='about'&&<AboutPage/>} {page==='profile'&&<Profile member={selected} edit={edit} contacts={contacts} loggedIn={loggedIn} logout={logout} login={login} activity={profileActivity}/>} {page==='management'&&<Management form={form} setForm={setForm} saveMember={saveMember} editing={editing} cancel={()=>{setEditing(null);setForm(blank)}} members={members} edit={edit} del={del}/>} {page==='submit'&&<SubmitContent/>} {(page==='calendar'||page==='reminder')&&<CalendarPage openProfile={openProfile} members={members} events={calendarEvents} setEvents={setCalendarEvents} currentMember={selected}/>} {page==='notifications'&&<Notifications events={calendarEvents} setPage={setPage}/>}</main><footer className="avit"><p>DESIGNED & DEVELOPED BY</p><h2>Av<span>i</span>T Solutions</h2><h3>Websites • Mobile Apps • Custom Software • Audio Visual Complete Solutions</h3><b>www.avitsolutions.tech</b></footer><div className="bottom"><button onClick={()=>setPage('home')}><Home/>Home</button><button onClick={()=>setPage('directory')}><Users/>Directory</button><button className="plus" aria-label="Submit" onClick={()=>setPage('submit')}><Plus/></button><button onClick={()=>setPage('calendar')}><CalendarDays/>Calendar</button><button onClick={()=>setPage('profile')}><UserCircle/>Profile</button></div>{toast&&<div className="toast"><CheckCircle2/>{toast}</div>}</div>}
function HomePage({members,calendarEvents=[],setPage,openProfile}){return <><section className="hero"><div><p className="eyebrow">Business Excellence Group • Since 2017</p><h1>Connecting entrepreneurs, professionals and industry leaders.</h1><p>AMBI is the members-only digital platform for the Business Excellence Group, built around verified member profiles, business sectors, events, RSVP, announcements and digital visiting cards.</p><div className="heroActions"><button onClick={()=>setPage('directory')}>Explore Directory <ChevronRight/></button><button onClick={()=>setPage('submit')}>Submit Announcement <Plus/></button></div></div><div className="heroCard"><img src="/ambi-logo.png"/><b>{members.length}</b><span>approved BEG members</span></div></section><section className="stats"><div><b>{members.length}</b><span>Approved Members</span></div><div><b>{new Set(members.map(m=>m.category)).size}</b><span>Active Sectors</span></div><div><b>{calendarEvents.filter(e=>!e.blocked).length}</b><span>Calendar Items</span></div><div><b>2017</b><span>BEG Established</span></div></section><section className="panel"><div className="sectionHead"><h2>Featured members</h2><button onClick={()=>setPage('directory')}>View all</button></div><div className="memberGrid">{members.slice(0,4).map(m=><MemberCard key={m.id} m={m} openProfile={openProfile}/>)}</div></section></>}

function AboutPage(){return <><section className="pageHero"><p className="eyebrow">About the Business Excellence Group</p><h1>Built from a collective voice for business progress.</h1><p>The Business Excellence Group was created in 2017 as a common platform for young emerging business establishments, entrepreneurs and professionals to share ideas, strengthen relationships and give meaningful direction toward greater goals.</p></section><section className="stats"><div><b>2017</b><span>Founded</span></div><div><b>BEG</b><span>Registered Society, Manipur</span></div><div><b>15+</b><span>Business Sectors</span></div><div><b>SYNERGY</b><span>Business Summit</span></div></section><section className="panel story"><h2>Our journey</h2><p>In a short span of time, BEG has emerged as a forward-thinking and progressive organisation in the trade and commerce ecosystem. Government departments, institutions, trade bodies and prominent establishments recognise BEG as a growing collective of first-generation business enterprises, entrepreneurs and professionals.</p><p>What started as a rendezvous to share ideas and experiences soon grew into a vibrant network. Members represent diverse sectors including manufacturing, hospitality, healthcare, education, e-commerce, retail, automobiles, real estate, construction, IT, finance, cosmetics, FMCG, food and beverage and more.</p></section><section className="panel story"><h2>Community and economic engagement</h2><p>BEG has supported humanitarian initiatives from flood relief to COVID-19 assistance, including the distribution of food and essential items to children’s homes, de-addiction centres and differently abled centres.</p><p>To strengthen economic relationships, BEG has participated in national and international conclaves. SYNERGY, a business summit with Myanmar business delegates, created an important platform for dialogue between enterprises of Manipur and neighbouring regions.</p></section></>}

function Directory({members,sectors,cat,setCat,query,setQuery,openProfile}){return <><section className="pageHero"><p className="eyebrow">AMBI real member directory</p><h1>Find approved BEG members by business sector.</h1><p>All records in this directory are installed from the approved AMBI/BEG member list. Missing photos or logos can be added later from the member profile editor.</p><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search member name, company, service, sector..."/></div></section><section className="sectors">{sectors.map(s=><button key={s.name} className={cat===s.name?'active':''} onClick={()=>setCat(s.name)}><span className="sectorIcon">{CATEGORY_ICONS[s.name]||'📋'}</span><b>{s.name}</b><span>{s.count} members</span></button>)}</section><section className="memberGrid wide">{members.map(m=><MemberCard key={m.id} m={m} openProfile={openProfile}/>)}</section>{members.length===0&&<div className="empty">No members found. Try another search or category.</div>}</>}
function MemberCard({m,openProfile}){return <button className="memberCard" onClick={()=>openProfile(m)}><Avatar m={m}/><div><h3>{m.name}</h3><p>{m.company}</p><span>{m.category}</span><small><ShieldCheck/> Verified Member</small></div><ChevronRight/></button>}
function Profile({member,edit,contacts=[],loggedIn=true,logout,login,activity=[]}){if(!loggedIn){return <section className="pageHero profileLogin"><p className="eyebrow">Member profile</p><h1>You are logged out.</h1><p>Log in to view your name, details, visiting card, contacts, connections and activity history.</p><button onClick={login}><UserCircle/> Log in as member</button></section>}if(!member)return <section className="pageHero"><h1>Profile not found</h1></section>;const history=[...activity,{id:'profile-update',type:'Profile',title:'Digital visiting card ready',status:'Completed',date:'Today',approvedBy:member.approvedBy||'Committee Admin'}];const ads=history.filter(h=>/ad|advertisement|promotion|poster|announcement/i.test(`${h.type} ${h.title}`));return <><section className="profileCover profileCoverClean"><Avatar m={member} big/><div className="profileTitleBlock"><p className="eyebrow">My verified profile</p><h1>{member.name}</h1><p>{member.position||'Member'} • {member.company}</p><p className="profileApproved">Verified by {member.approvedBy||'Committee Admin'}</p></div><button className="logoutBtn" onClick={logout}>Logout</button></section><section className="profileDashboard"><div className="profileMain"><div className="panel profileDetailsCard"><div className="sectionHead"><div><p className="eyebrow">Your details</p><h2>Member information</h2></div><button onClick={()=>edit(member)}><Edit3/> Edit profile</button></div><div className="profileInfoRows"><p><b>Name</b><span>{member.name}</span></p><p><b>Company</b><span>{member.company}</span></p><p><b>Position</b><span>{member.position||'Member'}</span></p><p><b>Category</b><span>{member.category}</span></p><p><b>Email</b><span>{member.email||'Not provided'}</span></p><p><b>Phone</b><span>{member.phone||'Hidden or not provided'}</span></p><p><b>Address</b><span>{member.address||'Not provided'}</span></p></div><h2>About</h2><p>{member.about||'Business profile introduction will appear here.'}</p><h2>Services</h2><div className="chips">{(member.services||member.category||'Member').split(',').map(x=><span key={x}>{x.trim()}</span>)}</div></div><div className="panel"><div className="sectionHead"><div><p className="eyebrow">History</p><h2>Your activity</h2></div><span className="historyCount">{history.length}</span></div><div className="historyList">{history.map(h=><div key={h.id} className="historyItem"><div><b>{h.title}</b><small>{h.type} • {h.date}</small></div><span className={h.status==='Approved'||h.status==='Completed'?'ok':'wait'}>{h.status}</span></div>)}</div></div></div><aside className="profileSide"><div className="vcard profileVcard"><div className="vfront"><Avatar m={member}/><h2>{member.name}</h2><p>{member.company}</p><small>{member.email||'Email not provided'}</small><small>{member.phone||'Phone hidden'}</small></div><div className="vback"><h3>Services</h3><p>{member.services||member.category}</p><button><Share2/> Share digital card</button><button><Download/> Download card</button></div></div><div className="panel profileMiniPanel"><p className="eyebrow">Contacts</p><h2>Who you contacted</h2>{contacts.length?contacts.map(c=><div className="contactRow" key={c.id}><b>{c.name}</b><small>{c.company} • {c.date}</small></div>):<p className="mutedText">No contact history yet. Open a member from Directory to add them here.</p>}</div><div className="panel profileMiniPanel"><p className="eyebrow">Connections & posts</p><h2>Summary</h2><div className="profileStats"><div><b>{contacts.length}</b><span>Contacts</span></div><div><b>{Math.max(contacts.length-1,0)}</b><span>Connections</span></div><div><b>{ads.length}</b><span>Ads / posts</span></div></div></div></aside></section></>}

function Management({form,setForm,saveMember,editing,cancel,members,edit,del}){function up(k,v){setForm({...form,[k]:v})}return <><section className="pageHero"><p className="eyebrow">Management portal</p><h1>{editing?'Edit member profile':'Add new member to directory'}</h1><p>Committee-only area for adding approved members, updating business profiles, and controlling how each member appears in the directory.</p></section><section className="builder"><form onSubmit={e=>{e.preventDefault();saveMember()}}><div className="two"><label>Name<input value={form.name} onChange={e=>up('name',e.target.value)} placeholder="Member real name"/></label><label>Position<input value={form.position} onChange={e=>up('position',e.target.value)} placeholder="Proprietor / Director"/></label></div><label>Company<input value={form.company} onChange={e=>up('company',e.target.value)} placeholder="Company name"/></label><div className="two"><label>Category<select value={form.category} onChange={e=>up('category',e.target.value)}>{SECTORS.filter(x=>x!=='All').map(x=><option key={x}>{x}</option>)}</select></label><label>Email<input value={form.email} onChange={e=>up('email',e.target.value)} placeholder="email@example.com"/></label></div><div className="two"><label>Phone<input value={form.phone} onChange={e=>up('phone',e.target.value)} placeholder="Optional"/></label><label>Address<input value={form.address} onChange={e=>up('address',e.target.value)} placeholder="Imphal, Manipur"/></label></div><label>Services<textarea value={form.services} onChange={e=>up('services',e.target.value)} placeholder="List services separated by commas"/></label><label>About<textarea value={form.about} onChange={e=>up('about',e.target.value)} placeholder="Short company/member introduction"/></label><div className="uploads"><label><Upload/> Upload personal photo<input type="file" accept="image/*" onChange={e=>readFile(e.target.files[0],v=>up('photo',v))}/>{form.photo&&<span>Photo uploaded</span>}</label><label><ImageIcon/> Upload company logo<input type="file" accept="image/*" onChange={e=>readFile(e.target.files[0],v=>up('logo',v))}/>{form.logo&&<span>Logo uploaded</span>}</label></div><fieldset><legend>Directory display preference</legend>{['photo','logo','initials'].map(x=><label key={x} className="radio"><input type="radio" checked={form.display===x} onChange={()=>up('display',x)}/>{x==='photo'?'Show personal photo':x==='logo'?'Show company logo':'Show initials only'}</label>)}</fieldset><div className="actions"><button type="submit"><Save/> {editing?'Update member':'Save member'}</button>{editing&&<button type="button" onClick={cancel}>Cancel edit</button>}</div></form><aside className="preview"><h2>Directory preview</h2><MemberCard m={{...form,name:form.name||'Member Name',company:form.company||'Company Name'}} openProfile={()=>{}}/><div className="vfront"><Avatar m={{...form,name:form.name||'Member Name',company:form.company||'Company Name'}}/><h2>{form.name||'Member Name'}</h2><p>{form.company||'Company Name'}</p><small>{form.email||'email@example.com'}</small></div></aside></section><section className="panel"><div className="sectionHead"><h2>Existing members</h2><span>{members.length} records</span></div><div className="tableList">{members.map(m=><div key={m.id}><Avatar m={m}/><b>{m.name}</b><span>{m.company}</span><button onClick={()=>edit(m)}><Edit3/></button><button onClick={()=>del(m.id)}><Trash2/></button></div>)}</div></section></>}

function CalendarPage({members,openProfile,events,setEvents,currentMember}){
  const todayMonth=5;
  const [view,setView]=useState('month');
  const [sound,setSound]=useState(true);
  const [showCreate,setShowCreate]=useState(false);
  const [selectedMonth,setSelectedMonth]=useState(todayMonth);
  const visibleEvents=useMemo(()=>events.filter(ev=>!ev.blocked),[events]);
  const monthEvents=useMemo(()=>visibleEvents.filter(ev=>dateParts(eventKeyDate(ev)).month===selectedMonth),[visibleEvents,selectedMonth]);
  const [selectedEventId,setSelectedEventId]=useState(monthEvents[0]?.id||visibleEvents[0]?.id||'');
  useEffect(()=>{if(!visibleEvents.some(ev=>ev.id===selectedEventId)){setSelectedEventId(monthEvents[0]?.id||visibleEvents[0]?.id||'')}},[visibleEvents.length,selectedMonth]);
  const selectedEvent=visibleEvents.find(ev=>ev.id===selectedEventId)||monthEvents[0]||visibleEvents[0];
  const [draft,setDraft]=useState({title:'',date:`2026-${String(selectedMonth+1).padStart(2,'0')}-24`,time:'4:00 PM',location:'BEG Office',type:'Member Event',createdBy:currentMember?.name||'Verified Member'});
  const firstDay=new Date(2026,selectedMonth,1).getDay();
  const daysInMonth=new Date(2026,selectedMonth+1,0).getDate();
  const cells=[...Array(firstDay).fill(null),...Array.from({length:daysInMonth},(_,i)=>i+1)];
  while(cells.length%7!==0)cells.push(null);
  const eventByDay=(day)=>monthEvents.filter(ev=>dateParts(eventKeyDate(ev)).day===day);
  const findMember=(name)=>members.find(m=>m.name===name);
  const attendeeNames=selectedEvent?[...(selectedEvent.attending||[]),...(selectedEvent.maybe||[]),...(selectedEvent.not||[])]:[];
  const attendeeMembers=attendeeNames.map(findMember).filter(Boolean);
  const companies=[...new Set(attendeeMembers.map(m=>m.company))];
  const total=selectedEvent?(selectedEvent.attending||[]).length+(selectedEvent.maybe||[]).length+(selectedEvent.not||[]).length:0;
  function triggerSound(){if(!sound)return;try{new Audio('data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAESsAACJWAAACABAAZGF0YQAAAAA=').play().catch(()=>{})}catch{}}
  function doRsvp(status){
    if(!selectedEvent)return;
    const name=currentMember?.name||'Verified Member';
    setEvents(list=>list.map(ev=>{
      if(ev.id!==selectedEvent.id)return ev;
      const clean={...ev,attending:(ev.attending||[]).filter(n=>n!==name),maybe:(ev.maybe||[]).filter(n=>n!==name),not:(ev.not||[]).filter(n=>n!==name)};
      const key=status==='attending'?'attending':status==='maybe'?'maybe':'not';
      return {...clean,[key]:[...(clean[key]||[]),name]};
    }));
    triggerSound();
  }
  function saveEvent(){
    if(!draft.title.trim())return;
    const ev={id:'cal-'+Date.now(),title:draft.title.trim(),date:draft.date,time:draft.time||'All day',location:draft.location||'AMBI',type:draft.type||'Member Event',createdBy:currentMember?.name||draft.createdBy||'Verified Member',source:'Member-created calendar item',attending:[],maybe:[],not:[],blocked:false};
    setEvents(list=>[ev,...list]);
    setSelectedMonth(dateParts(ev.date).month);
    setSelectedEventId(ev.id);
    setShowCreate(false);
    setDraft({title:'',date:ev.date,time:'4:00 PM',location:'BEG Office',type:'Member Event',createdBy:currentMember?.name||'Verified Member'});
  }
  function blockEvent(id){setEvents(list=>list.map(ev=>ev.id===id?{...ev,blocked:true,blockedBy:'Admin'}:ev))}
  function deleteEvent(id){setEvents(list=>list.filter(ev=>ev.id!==id))}
  return <>
    <section className="pageHero reminderHero"><p className="eyebrow">Calendar</p><h1>Member calendar, holidays and RSVP.</h1><p>Approved members can create calendar items directly. They appear immediately for everyone. Admins can remove or block inappropriate items.</p><div className="heroActions"><button onClick={()=>setShowCreate(true)}><Plus/>Create Event</button><button onClick={()=>setSound(!sound)}><Bell/>{sound?'Sound On':'Sound Off'}</button></div></section>
    <section className="calendarAppV16">
      <aside className="calendarRailV16"><div className="miniYearV16"><button onClick={()=>setSelectedMonth(Math.max(0,selectedMonth-1))}>‹</button><b>2026</b><button onClick={()=>setSelectedMonth(Math.min(11,selectedMonth+1))}>›</button></div>{Array.from({length:12},(_,i)=><button key={i} className={i===selectedMonth?'active':''} onClick={()=>setSelectedMonth(i)}><span>{monthName(i)}</span><b>{visibleEvents.filter(ev=>dateParts(eventKeyDate(ev)).month===i).length}</b></button>)}</aside>
      <div className="calendarMainV16"><div className="calendarHeaderV16"><div><p className="eyebrow">{monthName(selectedMonth)} 2026</p><h2>AMBI Calendar</h2></div><div className="viewToggleV16"><button className={view==='month'?'active':''} onClick={()=>setView('month')}>Month</button><button className={view==='list'?'active':''} onClick={()=>setView('list')}>List</button></div></div>{view==='month'?<><div className="weekdaysV16">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><b key={d}>{d}</b>)}</div><div className="monthGridV16">{cells.map((day,i)=>day?<button key={i} className={`${eventByDay(day).length?'hasEvent':''} ${selectedEvent&&dateParts(eventKeyDate(selectedEvent)).day===day&&dateParts(eventKeyDate(selectedEvent)).month===selectedMonth?'selected':''}`} onClick={()=>{const ev=eventByDay(day)[0]; if(ev)setSelectedEventId(ev.id)}}><span className="dayNumV16">{day}</span>{eventByDay(day).slice(0,3).map(ev=><small key={ev.id}>{ev.title}</small>)}</button>:<button key={i} className="blankDayV19" disabled></button>)}</div></>:<div className="eventListFullV16">{monthEvents.map(ev=><button key={ev.id} className={selectedEvent?.id===ev.id?'active':''} onClick={()=>setSelectedEventId(ev.id)}><b>{dateParts(eventKeyDate(ev)).day}</b><div><strong>{ev.title}</strong><small>{ev.time} · {ev.location}</small></div><span>{(ev.attending||[]).length} attending</span></button>)}</div>}</div>
      <aside className="eventDeskV16">{selectedEvent?<><div className="eventBadgeV16"><CalendarDays/><span>{selectedEvent.type||'Calendar Item'}</span></div><h2>{selectedEvent.title}</h2><p>{eventKeyDate(selectedEvent)} · {selectedEvent.time} · {selectedEvent.location}</p><small>Created by {selectedEvent.createdBy}. No approval required.</small><div className="rsvpStatsV16"><div><b>{(selectedEvent.attending||[]).length}</b><span>Attending</span></div><div><b>{(selectedEvent.maybe||[]).length}</b><span>Maybe</span></div><div><b>{(selectedEvent.not||[]).length}</b><span>Not</span></div></div><div className="rsvpButtonsV16"><button onClick={()=>doRsvp('attending')}>Attending</button><button onClick={()=>doRsvp('maybe')}>Maybe</button><button onClick={()=>doRsvp('not')}>Not Attending</button></div><div className="attendeeTabsV16"><h3>Attendee Directory</h3><AttendeeGroup title="Attending" names={selectedEvent.attending||[]} members={members} openProfile={openProfile}/><AttendeeGroup title="Maybe" names={selectedEvent.maybe||[]} members={members} openProfile={openProfile}/><AttendeeGroup title="Not Attending" names={selectedEvent.not||[]} members={members} openProfile={openProfile}/></div><div className="companiesV16"><h3>Attending Companies</h3>{companies.length?companies.map(c=><span key={c}>{c}</span>):<small>No company list yet.</small>}</div><div className="adminControlsV19"><h3>Admin controls</h3><button onClick={()=>blockEvent(selectedEvent.id)}><ShieldCheck/>Block event</button><button onClick={()=>deleteEvent(selectedEvent.id)}><Trash2/>Delete event</button></div></>:<p>No calendar item selected.</p>}</aside>
    </section>
    <section className="panel eventNetworkPanelV16"><div className="sectionHead"><div><p className="eyebrow">Event Network</p><h2>{total} member responses connected to verified profiles</h2></div><button><Share2/>Share Event</button></div><div className="eventMemberStripV16">{attendeeMembers.map(m=><button key={m.id} onClick={()=>openProfile(m)}><Avatar m={m}/><b>{m.name}</b><small>{m.company}</small></button>)}</div></section>
    {showCreate&&<div className="modalOverlayV16" onClick={()=>setShowCreate(false)}><div className="createEventModalV16" onClick={e=>e.stopPropagation()}><div className="sectionHead"><div><p className="eyebrow">Create Calendar Item</p><h2>Post directly to Calendar</h2></div><button onClick={()=>setShowCreate(false)}>Close</button></div><div className="two"><label>Event Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="Example: Business Networking Evening"/></label><label>Date<input type="date" value={draft.date} onChange={e=>setDraft({...draft,date:e.target.value})}/></label></div><div className="two"><label>Time<input value={draft.time} onChange={e=>setDraft({...draft,time:e.target.value})}/></label><label>Location<input value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label></div><label>Type<select value={draft.type} onChange={e=>setDraft({...draft,type:e.target.value})}><option>Member Event</option><option>Business Meeting</option><option>Announcement</option><option>Holiday / Observance</option></select></label><div className="successMsg"><CheckCircle2/> This will appear on the calendar immediately. Admin can block or delete later if required.</div><button onClick={saveEvent}><CheckCircle2/>Save to Calendar</button></div></div>}
  </>
}
function AttendeeGroup({title,names,members,openProfile}){return <div className="attendeeGroupV16"><div className="attendeeGroupHeadV16"><b>{title}</b><span>{names.length}</span></div>{names.length?names.map(name=>{const m=members.find(x=>x.name===name);return <button key={name} onClick={()=>m&&openProfile(m)}>{m?<Avatar m={m}/>:<div className="avatarMono mini">{name.slice(0,2).toUpperCase()}</div>}<div><strong>{name}</strong><small>{m?.company||'Verified Member'}</small></div><ChevronRight size={15}/></button>}):<small className="emptyMiniV16">No responses yet.</small>}</div>}

function SubmitContent(){const [asset,setAsset]=useState(null);const [kind,setKind]=useState('Advertisement');const [title,setTitle]=useState('');const [summary,setSummary]=useState('');const [details,setDetails]=useState('');const [msg,setMsg]=useState('');function fileUp(file){if(!file)return;readFile(file,v=>setAsset({name:file.name,type:file.type,src:v}))}function submit(e){e.preventDefault();if(!title||!summary){setMsg('Please add a title and short summary before submitting.');return}setMsg('Submitted for committee approval. Approved items will show with the approving admin name.')}return <><section className="pageHero"><p className="eyebrow">Member submission</p><h1>Submit an announcement, report or advertisement.</h1><p>Use this form for member promotions, notices, event reports, offers or public announcements. Submissions stay pending until approved by a committee admin.</p></section><section className="builder submitClean"><form onSubmit={submit}><label>Submission type<select value={kind} onChange={e=>setKind(e.target.value)}><option>Advertisement</option><option>Announcement</option><option>Event Notice</option><option>Business Offer</option><option>Report</option></select></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Example: Business networking dinner"/></label><label>Short summary<textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Write a short summary for admin review and public preview."/></label><label className="submitUpload"><Upload/> Upload poster, banner, photo or PDF<input type="file" accept="image/*,.pdf" onChange={e=>fileUp(e.target.files[0])}/>{asset&&<span>{asset.name}</span>}</label><label>Full details<textarea value={details} onChange={e=>setDetails(e.target.value)} placeholder="Add full details, date, location, contact or supporting information."/></label><button type="submit"><Save/> Submit for Approval</button>{msg&&<div className="successMsg">{msg}</div>}</form><aside className="preview"><h2>Submission preview</h2><div className="contentPreviewCard"><span>{kind}</span><h3>{title||'Submission title'}</h3><p>{summary||'Short summary will appear here.'}</p>{asset&&asset.type.startsWith('image/')?<img src={asset.src}/>:asset&&<b>PDF attached: {asset.name}</b>}<small>Status: Pending approval</small></div></aside></section></>}
function Notifications({events=[],setPage}){const upcoming=events.filter(e=>!e.blocked).slice(0,6);return <><section className="pageHero"><p className="eyebrow">Notifications</p><h1>Member alerts and calendar reminders</h1><p>Latest AMBI alerts, calendar items and member notices. Use Calendar for RSVP and full event details.</p></section><section className="panel"><div className="sectionHead"><h2>Important alerts</h2><button onClick={()=>setPage('calendar')}><CalendarDays/>Open Calendar</button></div>{notificationSeed.map(n=><div className="notice" key={n.t}><Bell/><div><h3>{n.t}</h3><p>{n.d}</p></div></div>)}{upcoming.map(ev=><div className="notice" key={ev.id}><CalendarDays/><div><h3>{ev.title}</h3><p>{eventKeyDate(ev)} · {ev.time} · {ev.location}</p></div></div>)}</section></>}
createRoot(document.getElementById('root')).render(<App/>);
